version: '3'

services:
  app:
    build: .

    networks:
      - default
    ports:
      - "8000:8000"
    environment:
      - AUTHOR=Rodrigo Barbosa Lima
    volumes:
      - .:/code
    command: /code/start.sh