# Generated by Django 3.2.7 on 2021-10-02 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome do artista')),
                ('artistic_name', models.CharField(max_length=80, verbose_name='Nome artístico')),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=12, unique=True, verbose_name='RG')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de criação')),
            ],
        ),
    ]
